apiVersion: v1
kind: Service

metadata:
  name: result
  labels:
    app: result-service
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - port: 8089
      targetPort: 80
      nodePort: 32000
