apiVersion: v1
kind: Service

metadata:
  name: vote
  labels:
    app: vote-service
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - port: 8088
      targetPort: 80
      nodePort: 31000
